# 1. Use Java base image
FROM openjdk:21-jdk-slim

# 2. Set working directory inside container
WORKDIR /app

# 3. Copy JAR file into container
COPY target/Ecom-website.jar app.jar

# 4. Expose application port
EXPOSE 8081

# 5. Command to run the app
ENTRYPOINT ["java","-jar","app.jar"]
